### ISSUE TITLE
Is there any published reports related to this code?

### ISSUE THREAD

**Issue by XavierNie715** [Tianshu-Liu/OpenOpticalFlow_PIV_v1#1]

**Comment by Tianshu-Liu** [comment]
The paper related to this software is
T. Liu and D. Salazar “OpenOpticalFlow_PIV: an open source program integrating optical flow method with cross-correlation method for particle image velocimetry,” Journal of Open Research Software, Vol. 9, No. 1, p. 3 (2021).

Tianshu


________________________________
From: Xavier.Nie ***@***.***>
Sent: Sunday, November 13, 2022 2:06 AM
To: Tianshu-Liu/OpenOpticalFlow_PIV_v1 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Tianshu-Liu/OpenOpticalFlow_PIV_v1] Is there any published reports related to this code? (Issue #1)


Attention: This email is from outside Western Michigan University. Use caution when opening links and attachments.
